[workspace]
resolver = "2"
members = [
    "gigacare-core",
    "gigacare-config",
    "gigacare-fs",
    "gigacare-hash",
    "gigacare-license",
    "gigacare-quarantine",
    "gigacare-vision",
    "gigacare-ai",
]

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ready2devs/gigacare"